module.exports = {
  alps: require("./alps"),
  button: require("./button"),
  button_reversible: require("./button_reversible"),
  choc: require("./choc"),
  chocmini: require("./chocmini"),
  diode: require("./diode"),
  jstph: require("./jstph"),
  "jst_0.1mm_1x4_horiz": require("./jst_0.1mm_1x4_horiz"),
  jumper: require("./jumper"),
  mx: require("./mx"),
  oled: require("./oled"),
  omron: require("./omron"),
  pad: require("./pad"),
  promicro: require("./promicro"),
  promicro_pretty: require("./promicro_pretty"),
  rgb: require("./rgb"),
  rotary: require("./rotary"),
  scrollwheel: require("./scrollwheel"),
  slider: require("./slider"),
  trrs: require("./trrs"),
  via: require("./via"),

  sample_conn_molex_pico_ezmate_1x02: require("./sample_conn_molex_pico_ezmate_1x02"),
  sample_reset_switch: require("./sample_reset_switch"),
  sample_jst_battery_connector: require("./sample_jst_battery_connector"),
  sample_nice_view: require("./sample_nice_view"),
};
